# Generated by Django 5.0.6 on 2024-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatorydocument',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='regulatorydocument',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='regulatory_documents', to='apis.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Исполнено', 'Исполнено'), ('Не исполнено', 'Не исполнено')], default='Не исполнено', max_length=100),
        ),
    ]
