# Generated by Django 5.0.6 on 2024-06-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_regulatorydocument_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
