# Generated by Django 5.0.6 on 2024-06-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_task_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='regulation',
            field=models.ManyToManyField(blank=True, related_name='tasks_of_regulation', to='apis.regulatorydocument'),
        ),
    ]
