# Generated by Django 5.0.6 on 2024-06-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_task_regulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatorydocument',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='regulation',
        ),
        migrations.AddField(
            model_name='task',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_of_regulation', to='apis.regulatorydocument'),
        ),
    ]
