# Generated by Django 5.0.6 on 2024-06-28 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_regulatorydocument_tasks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='co_executors',
            field=models.ManyToManyField(blank=True, null=True, related_name='co_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
